typography_spectrum: 0.4504686160944402
color:
  brandStrength: 0.9566408274695277
  lightness: 0.2443490184377879
  saturation: 0.6951741671655327
  rhythmicContrast: 0.8004383284132928
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.9384557751473039
name: artificial history
navigation:
  - name: Travel Blog
    url: 'http://packit.in'
    type: external
  - name: Portfolio
    url: 'http://jamiearcher.co.uk'
    type: external
title: thoughts of sorts
